### ISSUE TITLE
Cannot run in android studio

### ISSUE THREAD

**Issue by lapamplemousse** [abritopach/ionic-test-capacitor-youtube-player#1]
When I run this plugin on the web view it works fine. However when I try to run in android studio I get the following error

     E/Capacitor/Plugin/Console: ERROR Error: Uncaught (in promise): TypeError: Cannot read 
     property 'initialize' of undefined
    TypeError: Cannot read property 'initialize' of undefined
        at YoutubePage.<anonymous> (http://localhost/youtube-youtube-module.js:3086:60)
        at step (http://localhost/vendor.js:122096:23)
        at Object.next (http://localhost/vendor.js:122077:53)
        at http://localhost/vendor.js:122070:71
        at new ZoneAwarePromise (http://localhost/polyfills.js:191386:29)
        at Module.__awaiter (http://localhost/vendor.js:122066:12)
        at YoutubePage.push../src/app/youtube/youtube.page.ts.YoutubePage.initializeYoutubePlayerPluginNative (http://localhost/youtube-youtube-module.js:3078:63)
        at YoutubePage.push../src/app/youtube/youtube.page.ts.YoutubePage.ngAfterViewInit 
       (http://localhost/youtube-youtube-module.js:3041:18)
        at callProviderLifecycles (http://localhost/vendor.js:58539:18)
        at callElementProvidersLifecycles (http://localhost/vendor.js:58513:13)

**Comment by Sevensnake** [comment]
I am having the same problem with the most current version "^1.0.0-alpha.1-55",
